volumes:
  mysqldb:
  webstorage:

networks:
  internal_network:
    driver: bridge

services:
  app:
    container_name: app
    build: .
    volumes:
      - webstorage:/var/www/html/storage
    ports:
      - "8080:8080"
    networks:
      - default
      - internal_network
    environment:
      DOCKER_ENV: 1
      MYSQL_DATABASE: bssb
      MYSQL_USER: bssb
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SENTRY_DSN: ${SENTRY_DSN}
      CACHE_ENABLED: ${CACHE_ENABLED}
      HASHIDS_SALT: ${HASHIDS_SALT}
      STEAM_WEB_API_KEY: ${STEAM_WEB_API_KEY}
      MASTER_SERVER_BLACKLIST: ${MASTER_SERVER_BLACKLIST}
      TWITTER_API_KEY: ${TWITTER_API_KEY}
      TWITTER_API_KEY_SECRET: ${TWITTER_API_KEY_SECRET}
    depends_on:
      - db
      - redis
    restart: always

  db:
    container_name: mysql
    image: percona/percona-server
    volumes:
      - mysqldb:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - internal_network
    environment:
      MYSQL_DATABASE: bssb
      MYSQL_USER: bssb
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    restart: always

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - internal_network
    restart: always